### ISSUE TITLE
"Requesting access" delay in Wave Portal if users have registered their devices

### ISSUE THREAD

**Issue by sinak** [repeaterstore/celfi-feedback#2]
If a customer has already registered their device and we request access in the Wave Portal, we get the following message:

![image](https://user-images.githubusercontent.com/293798/53701198-74396380-3daf-11e9-94ed-3057892df9e3.png)

Access is sometimes granted within 10 to 20 minutes, but other times it takes much longer. We're often on the phone with a customer when we get their serial number, so the wait time is quite frustrating as we'd like to view their data immediately.

**Comment by sinak** [comment]
As an example, serial number `932847001530` took 10 hours today to gain access.

**Comment by dcbaeza** [comment]
Please try again and report any new instances of access request delays.  We recently fixed an issue where instant access was not being granted if there was an operator change.  The normal process required the distributor to grant access.   

With that being said, you can also enter the serial numbers upon receipt from the distributor or enter the serial numbers when you ship the equipment so the request would be granted prior to the customer troubleshooting session.

**Comment by sinak** [comment]
Will test and let you know. Thanks @dcbaeza!

**Comment by sinak** [comment]
This appears to be resolved. Thanks so much @dcbaeza!

**Comment by dcbaeza** [comment]
My pleasure.  Thanks for bringing it to our attention.
